(defclass booking ()
   (
		(start :accessor booking-start-date)
		(end :accessor booking-end-date)
		(room-number :accessor booking-room-number)
		(guest-id :accessor booking-guest-id)
		(people-count :accessor booking-people-count)
   )
)
(defmethod print-booking ((object booking))
   (format t "Guest With ID ~d " (booking-guest-id object))
	(format t " has booked room with id ~d" (booking-room-number object))
	(format t " from ~d" (booking-start-date object))
	(format t " to ~d" (booking-end-date object))
	(format t " with total of ~d" (booking-people-count object))
	(format t " People.~%")
)
( defmethod get-room-number ((object booking))
	(return-from get-room-number (booking-room-number object))
)